src/BetaMushroom/Controllers/MushroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BetaMushroom.Models;
using BetaMushroom.ViewModels;
using BetaMushroom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace BetaMushroom.Controllers
{
    public class MushroomController : Controller    
    {
        private ApplicationDbContext context;
        

        public MushroomController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Index()
        {
            IList<MushroomActivity> mushrooms = context.Mushrooms.Include(c => c.Type).ToList();
            return View(mushrooms);
        }


        

        


        
        

        

    }
}

src/BetaMushroom/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BetaMushroom.Models;
using BetaMushroom.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using BetaMushroom.Data.Migrations;
using BetaMushroom.ViewModels;



// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BetaMushroom.Controllers
{
    public class ProfileController : Controller
    {

        private readonly ApplicationDbContext _context;

        private UserManager<ApplicationUser> _userManager;
        private IHostingEnvironment _environment;
        

        
        public ProfileController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IHostingEnvironment environment)
        {
            _context = context;
            _userManager = userManager;
            _environment = environment;
        }


        public async Task<IActionResult> Index()
        {
            List<Profile> profiles = _context.Profiles.ToList();
            return View(await _context.Mushrooms.ToListAsync());
        }


        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profiles
                .SingleOrDefaultAsync(m => m.ID == id);

            if(profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        [HttpGet]
        public IActionResult Search()
        {
            ProfileSearchViewModel vm = new ProfileSearchViewModel();
            vm.MinAge = 18;
            vm.MaxAge = 100;
            
            
            
            return View(vm);

        }

        [HttpPost]
        public IActionResult Search(ProfileSearchViewModel vm)
        {
            List<ProfileSearchResultViewModel> result = new List<ProfileSearchResultViewModel>();
            if (ModelState.IsValid)
            {
                DateTime minDate = DateTime.Today.AddYears(-vm.MaxAge);
                DateTime maxDate = DateTime.Today.AddYears(-vm.MinAge);

                result = (from p in _context.Profiles
                          where p.Gender == vm.Gender
                          && p.Birthdate > minDate && p.Birthdate < maxDate

                          select new ProfileSearchResultViewModel
                          {
                              UserName = p.UserName,
                              ProfilePicture = $"{p.User.Id}/{p.ProfilePicture}",
                              Age = calculateAge(p.Birthdate),
                              Description = p.Description,                            
                              Gender = p.Gender,
                              ID = p.ID,


                          }
                          ).ToList();
            }
            return View("Result",result);
        }

        

        private int calculateAge(DateTime birthDate)
        {
            int age = DateTime.Today.Year - birthDate.Year;
            if(birthDate > DateTime.Today.AddYears(-age))
            {
                age--;
            }

            return age;
        }


        public IActionResult AddShroom(int id)
        {
            Profile profile = _context.Profiles.SingleOrDefault(p => p.ID == id);
            List<MushroomType> mushrooms = _context.Types.ToList();
            return View(new AddProfileShroomViewModel(profile, mushrooms));
        }

        [HttpPost]
        public IActionResult AddShroom(AddProfileShroomViewModel addProfileShroomViewModel)
        {
            if (ModelState.IsValid)
            {
                var mushroomID = addProfileShroomViewModel.MushroomID;
                var profileID = addProfileShroomViewModel.ProfileID;

                IList<ProfileShrooms> existingItems = _context.ProfileShrooms
                    .Where(pm => pm.ShroomID == mushroomID)
                    .Where(pm => pm.ProfileID == profileID).ToList();

                if(existingItems.Count == 0)
                {
                    ProfileShrooms profileShroom = new ProfileShrooms
                    {
                        ShroomID = mushroomID,
                        ProfileID = profileID
                    };

                    _context.ProfileShrooms.Add(profileShroom);
                    _context.SaveChanges();
                }
                return Redirect(string.Format("/Profile/ViewShrooms/{0}", addProfileShroomViewModel.ProfileID));
            }
            return View(addProfileShroomViewModel);
        }


        



        // GET: Profile/Edit/5
        public async Task<IActionResult> Edit()
        {

            ApplicationUser currentUser = await _userManager.GetUserAsync(User);

            var profile = await _context.Profiles.SingleOrDefaultAsync(m => m.ID == currentUser.ProfileId);


            return View(profile);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ID,UserName,Birthdate,Gender,Description,ProfilePicture,ProfilePictureFile,User")] Profile profile, IFormFile ProfilePictureFile)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(User);

                if(ProfilePictureFile != null)
                {
                    string uploadPath = Path.Combine(_environment.WebRootPath, "uploads");
                    Directory.CreateDirectory(Path.Combine(uploadPath, currentUser.Id));

                    string filename = Path.GetFileName(ProfilePictureFile.FileName);
                    


                    using (FileStream fs = new FileStream(Path.Combine(uploadPath, currentUser.Id, filename), FileMode.Create))
                    {
                        await ProfilePictureFile.CopyToAsync(fs);
                    }
                    profile.ProfilePicture = filename;


                }


                _context.Update(profile);
                await _context.SaveChangesAsync();
                
            }
            return View(profile);
        }
        

    }
}

src/BetaMushroom/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BetaMushroom.Controllers
{
    public class WelcomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Photos()
        {
            return View();
        }

    }
}

src/BetaMushroom/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE>
<html>
<head>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Mono' rel='stylesheet'
      3
      type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BetaMushroom</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css"S asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Welcome" asp-action="Index" class="navbar-brand">BetaMushroom</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--<li><a asp-area="" asp-controller="Account" asp-action="Login">Home</a></li>-->
                    
                    <!--<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>-->
                    <li><a asp-area="" asp-controller="Welcome" asp-action="Photos">Member Photos</a></li>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Profile" asp-action="Edit">My Profile</a></li>
                        <li><a asp-area="" asp-controller="Mushroom" asp-action="Index">My Collection</a></li>
                        <li><a href="@Url.Action("Search","Profile")">Search</a></li>

                    }

                    else
                    {
                        <!--<li><a href="@Url.Action("Register","Account")">Register Account</a></li>-->
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Home</a></li>

                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - BetaMushroom</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>