src/BetaMushroom/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BetaMushroom.Models;
using BetaMushroom.ViewModels;
using Microsoft.EntityFrameworkCore;
using BetaMushroom.Data;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace BetaMushroom.Controllers
{
    public class TypeController : Controller
    {
        private readonly ApplicationDbContext context;

        public TypeController(ApplicationDbContext dbContext)
        {
            context = dbContext;
        }
         

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<MushroomType> types = context.Types.ToList();
            return View(types);
        }

        public IActionResult Add()
        {
            AddTypeViewModel addTypeViewModel = new AddTypeViewModel();
            return View(addTypeViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddTypeViewModel addTypeViewModel)
        {
            if (ModelState.IsValid)
            {
                var theType = addTypeViewModel.Name;
                MushroomType newType = new MushroomType
                {
                    Name = theType
                };

                context.Types.Add(newType);
                context.SaveChanges();
                return Redirect("/Type/Index");
            }

            return View(addTypeViewModel);
        }
    }
}

src/BetaMushroom/Views/Type/Add.cshtml
@model BetaMushroom.ViewModels.AddTypeViewModel

<h1>This page will allow you to add different types of mushrooms to the database.</h1>

<form asp-controller="Type" asp-action="Add" method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>


    <input type="submit" />

</form>

src/BetaMushroom/Views/Type/Index.cshtml
@model IEnumerable<BetaMushroom.Models.MushroomType>


<h1>The different types of mushrooms in the database will be listed here.</h1>

@foreach (var type in Model)
{
    <ul>
        <li>
            @type.Name
            <br />
        </li>
    </ul>

}

<p><a asp-controller="Type" asp-action="Add">Add mushroom</a></p>